# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Edward Parkinson 
email: saultyevil@gmail.com 
author: Edward John Parkinson
description: > # "Write an awesome description for your new site here. 
  Description of the website.
copyright: 'Copyright &copy; 2020 Edward John Parkinson. All Rights Reserved.'
credits: 'Here are the credits' 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/douched_
  - title: github
    url: https://github.com/saultyevil
  - title: linkedin
    url: https://www.linkedin.com/in/edward-parkinson-86391613a/
