# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://edwardparkinson.co.uk
title: Edward John Parkinson 
email: saultyevil@gmail.com 
author: Edward John Parkinson
description: > 
  Personal website of Edward John Parkinson.
copyright: 'Copyright &copy; 2020 Edward John Parkinson. All Rights Reserved.'
credits: 'Inspired by the <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/saultyevil
  - title: linkedin
    url: https://www.linkedin.com/in/edward-parkinson-86391613a/
  - title: twitter
    url: https://twitter.com/douched_
  # - title: google
  #   url: mailto:saultyevil@gmail.com
  # - title: orcid
  # url: https://orcid.org/0000-0003-3902-052X